### ISSUE TITLE
storage directory creation causes permission issues with bref/php-82-fpm-dev:2

### ISSUE THREAD

**Issue by aknosis** [brefphp/laravel-bridge#117]
When storage directories are created for the first time they get created as `root:root` (due to being executed by bref hooks).

The issue is that web requests cannot write to the storage directory because fpm runs under the [nobody](https://github.com/brefphp/aws-lambda-layers/blob/main/layers/fpm/php-fpm.conf#L27) user and you end up with errors like below.

If I delete `/tmp/storage` after initial creation and fire a web request, it will happily create the storage directories as `nobody:nobody`.

Curious on thoughts of how to solve this.  

```
Exception: Unable to create lockable file: /tmp/storage/framework/cache/ec/c4/ecc49f49f4da6b940dcde13f0571e79c299871e6. Please ensure you have permission to create files in this location. in file /var/task/vendor/laravel/framework/src/Illuminate/Filesystem/LockableFile.php on line 73

#0 /var/task/vendor/laravel/framework/src/Illuminate/Filesystem/LockableFile.php(43): Illuminate\Filesystem\LockableFile->createResource('/tmp/storage/fr...', 'c+')
#1 /var/task/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(108): Illuminate\Filesystem\LockableFile->__construct('/tmp/storage/fr...', 'c+')
#2 /var/task/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(318): Illuminate\Cache\FileStore->add('a75f3f172bfb296...', 1683138765, 60)
#3 /var/task/vendor/laravel/framework/src/Illuminate/Cache/RateLimiter.php(118): Illuminate\Cache\Repository->add('a75f3f172bfb296...', 1683138765, 60)
#4 /var/task/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(149): Illuminate\Cache\RateLimiter->hit('a75f3f172bfb296...', 60)
...
```

**Comment by mnapoli** [comment]
Thank you for the detailed report and investigation!

Maybe a simple fix could be to chmod 777 the storage dir? Any downside?

**Comment by georgeboot** [comment]
Is this only an issue on the dev images, or on all fpm images?

**Comment by mnapoli** [comment]
> but I am curious why are we assigning the user to nobody?

IIRC this is because when running in Docker, things run as `root` and FPM doesn't like running as root.

**Comment by aknosis** [comment]
> Maybe a simple fix could be to chmod 777 the storage dir? Any downside?

I'm fine with this, I don't foresee any negative impact in the dev image or in Lambda

**Comment by nsaliu** [comment]
I'm using Osx and I always have this issue when restarting my Docker setup.

Apart from giving `777` to the `/tmp/storage` dir after the first request (when it's created), do you have any other tricks?
