### ISSUE TITLE
Cannot deploy project anymore

### ISSUE THREAD

**Issue by Adesin-fr** [brefphp/laravel-bridge#137]
New error since today, I can't understand why...
I did just pushed an update of my app online (no composer.lock change), and this happened.

Had the same issue a few seconds ago with OctaneHandler, so I disabled Octane, but now the Queue handler doesn't work anymore :(

Complete Error from bref dashboard : 
```
{
  "errorType": "Error",
  "errorMessage": "Object of type Bref\\LaravelBridge\\Queue\\QueueHandler is not callable",
  "stack": [
    "#0 /var/task/vendor/bref/bref/src/Runtime/Invoker.php(29): Bref\\FunctionRuntime\\Main::Bref\\FunctionRuntime\\{closure}(Array, Object(Bref\\Context\\Context))",
    "#1 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(89): Bref\\Runtime\\Invoker->invoke(Object(Closure), Array, Object(Bref\\Context\\Context))",
    "#2 /var/task/vendor/bref/bref/src/FunctionRuntime/Main.php(39): Bref\\Runtime\\LambdaRuntime->processNextEvent(Object(Closure))",
    "#3 /opt/bref/bootstrap.php(17): Bref\\FunctionRuntime\\Main::run()",
    "#4 {main}"
  ]
}
```

I've tested with an empty project and can reproduce the error (with Octane Handler)

Here is the repo with a demo empty laravel project which fails when you try to access the API endpoint : https://github.com/Adesin-fr/Bref-Failing-Project

**Comment by Adesin-fr** [comment]
Absolutely not related to laravel-bridge but to https://github.com/brefphp/bref/releases/tag/2.1.6 !
Had to revert back to 2.1.5 to get it working :)
