### ISSUE TITLE
Storage path is somehow being reset to default

### ISSUE THREAD

**Issue by damoncasale** [brefphp/laravel-bridge#166]
The storage path is somehow being reset to default, after the /tmp/storage paths are created.  Help?

Here's my CloudWatch log:

```
<!--StartFragment-->
INIT_START Runtime Version: provided:al2.v75	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:(obscured)
--
Creating storage directories: /tmp/storage/bootstrap/cache, /tmp/storage/framework/cache, /tmp/storage/framework/views, /tmp/storage/psysh
Running 'php artisan config:cache' to cache the Laravel configuration
INFO  Configuration cached successfully.
[23-Dec-2024 04:13:15] NOTICE: [pool default] 'user' directive is ignored when FPM is not running as root
[23-Dec-2024 04:13:15] NOTICE: fpm is running, pid 14
[23-Dec-2024 04:13:15] NOTICE: ready to handle connections
START RequestId: (obscured) Version: $LATEST
[2024-12-23 04:13:15] production.ERROR: The /var/task/bootstrap/cache directory must be present and writable. {"exception":"[object] (Exception(code: 0): The /var/task/bootstrap/cache directory must be present and writable. at /var/task/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php:179)
[stacktrace]
#0 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(132): Illuminate\\Foundation\\PackageManifest->write(Array)
#1 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(108): Illuminate\\Foundation\\PackageManifest->build()
#2 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(91): Illuminate\\Foundation\\PackageManifest->getManifest()
#3 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(80): Illuminate\\Foundation\\PackageManifest->config('aliases')
#4 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\\Foundation\\PackageManifest->aliases()
#5 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(316): Illuminate\\Foundation\\Bootstrap\\RegisterFacades->bootstrap(Object(Illuminate\\Foundation\\Application))
#6 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(187): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#7 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(171): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#8 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#9 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1190): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#10 /var/task/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest(Object(Illuminate\\Http\\Request))
#11 {main}
"}
END RequestId: (obscured)
REPORT RequestId: (obscured)	Duration: 202.42 ms	Billed Duration: 1130 ms	Memory Size: 2048 MB	Max Memory Used: 97 MB	Init Duration: 926.59 ms

<!--EndFragment-->
```

I'm using serverless to deploy a Laravel 11 application from a Github action, and attempting to make a single API call to that application.  Let me know what other information you need to debug this.

**Comment by mnapoli** [comment]
Can you provide more details: is this a brand new Bref and Laravel project? Or was it working before and stopped after upgrading? (if yes, upgrading what?)

Trying to understand if it is impacting everyone or related to something in your project that trips up the Laravel Bridge.

**Comment by damoncasale** [comment]
I've attempted to define a single API route which generates a PDF inside of a brand new Laravel 11 installation.  It works fine in a local environment (running on an Amazon EC2 instance) but errors running on Lambda.

Since it's difficult to trace what parameters are being passed in Lambda, I logged the manifest path to a file in my local environment (by adding some logging code to the PackageManifest.php file itself).  The manifest file isn't being written to the /tmp/storage folder, which is why this is erroring out.

**Comment by mnapoli** [comment]
I stumbled upon that error after accidentally adding `'!bootstrap/cache/**'` to the excluded patterns.

This was a mistake. I believe that what happens is that Laravel needs at least:

```
bootstrap/cache/packages.php
bootstrap/cache/services.php
```

to boot up (and then the Bref service provider can adjust the cache location).

These files are created (I believe) after `composer install` runs, in post-install scripts. So I think it would be fair to expect that these files always exist. If they don't, it means you need to run `composer install`.

Let's keep this issue open to see if others run into the problem. If you do, please detail why `bootstrap/cache` is deployed empty: is there a reason for that?
